# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 💥 Breaking changes
    labels:
      - breaking
  - title: 🚀 New features and improvements
    labels:
      - enhancement
  - title: 🐛 Bug fixes
    labels:
      - bug
  - title: Build Changes/Improvements
    labels:
      - build
  - title: 📝 Documentation updates
    labels:
      - documentation
  - title: 👻 Maintenance
    labels:
      - chore
      - maintenance
  - title: 🚦 Tests
    labels:
      - test
  - title: ✍ Other changes
  - title: 📦 Dependency updates
    labels:
      - dependency-upgrade
    collapse-after: 15
exclude-labels:
  - skip-changelog

template: |
  <!-- Optional: add a release summary here -->
  $CHANGES
